### ISSUE TITLE
Extend the Graph Extractor to extract a single repository

### ISSUE THREAD

**Issue by ftc** [cuplv/biggroum#50]
Create scripts to extract APK files into groum graphs inside of the Musedev docker container.

Sub tasks:
- [x] filter methods to extract based on files
- [x] script to run extractor on build directory
- [x] docker container setup

**Comment by ftc** [comment]
Script should download python files and jar to run graph extractor.

part of the groum/muse.sh file
[ ] do we have git as a dependency?
[ ] commit jar file to github
[ ] script to check out repository including jar file to run graph extractor
[ ] deploy script for docker container

They have a docker container.  We provide a shell script.  Our shell script downloads our dependencies and runs.

**Comment by smover** [comment]
Closed in #55 and https://github.com/cuplv/FixrGraphExtractor/pull/102
