### ISSUE TITLE
Musedev: Call Search Service From Biggroum Script

### ISSUE THREAD

**Issue by ftc** [cuplv/biggroum#52]
Write the code to send graphs and associated source files to the search service that runs the analysis.

**Comment by smover** [comment]
The code implementing the museapi is implemented in the [[https://github.com/cuplv/biggroum/blob/7ce8474ed0b01cd042941addbd4222595163346c/python/fixrgraph/musedev/api.py](api.py) file.

The integration of the service starts in the [https://github.com/cuplv/biggroum/blob/7ce8474ed0b01cd042941addbd4222595163346c/python/fixrgraph/musedev/api.py#L105](finalize) function: there is a list of TODO that you should implement to call the service.

**Comment by smover** [comment]
Closed in #53
