### ISSUE TITLE
Musedev: Implement the new Features in the Search Service

### ISSUE THREAD

**Issue by ftc** [cuplv/biggroum#53]
- [x] Create a new endpoint accepting a list of groums and source files.
- [x] Refactor implementation to be stateless with respect to previous runs.
- [x] Analysis on refactoring (note: don't remember the specifics of this, @smover could you look at the photo and update this point? it was item 5.2 on the whiteboard discussion 11/5/19)

**Comment by smover** [comment]
The following code show how to call the code that searches for anomalies and process the results.

The 1st task above should create the endpoint and get the data in the right format to call the following code.

```python
# Sample of code to call the anomaly extraction

# Create the "groum" index
# path_to_the_groums is the path to the extracted groums on the filesystem
# The groums must be organized in the path_to_the_groums as "username/reponame/commitid/"
# See the folder FixrGraphPatternSearch/fixrsearch/test/data/graphs for an example.
#
groum_index = GroumIndex(graph_path)

# Create a pull request proessor
pr_processor = PrProcessor(current_app.config[GROUM_INDEX],
                           Search(current_app.config[CLUSTER_PATH],
                                  current_app.config[ISO_PATH],
                                  current_app.config[CLUSTER_INDEX],
                                  current_app.config[GROUM_INDEX],
                                  current_app.config[TIMEOUT]),
                           current_app.config[SRC_CLIENT])

# Process the graphs from the app
commit_ref = CommitRef(RepoRef(repo_name, user_name), commit_hash)
anomalies = pr_processor.process_graphs_from_commit(commit_ref,
                                                    None)

# Process the anomaly in json
# This code must be changed to return also:
#   - the explanation of the anomaly, the pattern (see explain_anomaly)
#   - the patch (see inspect_anomaly)
json_data = []
for anomaly in anomalies:
    hack_link = "https://github.com/%s/%s/blob/%s/%s" % (
        anomaly.commit_ref.repo_ref.user_name,
        anomaly.commit_ref.repo_ref.repo_name,
        anomaly.commit_ref.commit_hash,
        anomaly.git_path
    )

    hackfn = "[%s](%s)" % (anomaly.method_ref.source_class_name,
                           hack_link)

    json_anomaly = {"id" : anomaly.numeric_id,
                    "error" : anomaly.description,
                    "packageName" : anomaly.method_ref.package_name,
                    "className" : anomaly.method_ref.class_name,
                    "methodName" : anomaly.method_ref.method_name,
                    "fileName" : hackfn,
                    "line" : anomaly.method_ref.start_line_number}

    logging.info("Found anomaly %s: " % str(json_anomaly))
    json_data.append(json_anomaly)
```

**Comment by smover** [comment]
When you finalize the output of the new endpoint we should update the apis:
- [ ]  [Convert the anomaly in a tool note](https://github.com/cuplv/biggroum/blob/7ce8474ed0b01cd042941addbd4222595163346c/python/fixrgraph/musedev/api.py#L139)
- [ ]  [Retrieving the pattern or the patch from an anomaly](https://github.com/cuplv/biggroum/blob/7ce8474ed0b01cd042941addbd4222595163346c/python/fixrgraph/musedev/api.py#L237)
- [ ] Update the related test cases

**Comment by phillip-wells** [comment]
@smover The anomaly search code doesn't seem to produce any useful output on our test files. Shawn and I looked into it, and it seems that instead of calling `process_graphs_from_commit` we ought to call `search_from_groum` from `search.py`. This also does not produce any output; for example, if we create a search instance and call on a specific groum, the output is `[]`:

```
search = Search(current_app.config[CLUSTER_PATH],
                        current_app.config[ISO_PATH],
                        current_app.config[CLUSTER_INDEX],
                        current_app.config[GROUM_INDEX],
                        current_app.config[TIMEOUT])

r = search.search_from_groum(graph_path + "cuplv/AwesomeApp/9d759f47dc6b7b404a32eafcbc654b134bf6778a/fixr.plv.colorado.edu.awesomeapp.MainActivity_recycleItems.acdfg.bin")

print(r)
```
Any help here would be much appreciated. Thanks!

**Comment by smover** [comment]
@phillip-wells `process_graphs_from_commit` is the right function to call.

`process_graphs_from_commit` process all the graphs of a commit and for each graph:
 1. call the `search_from_groum` function, finding a list of similar patterns;
2. creates the patch for each similar pattern that is marked as anomaly; and
3. packs all the anomaly as `Anomaly` object

So, `search_from_groum` does not do "enough" (no patch, no right formatting). Also, you should get the graph already organized in the "right way" on the filesystem to be used as input for `process_graphs_from_commit`.

I cannot comment more about you getting an empty result without seeing a concrete instance of the problem.
Could you point me to a test case I can use to test the service endpoint?

**Comment by ftc** [comment]
@smover the method `process_graphs_from_commit` appears to look up the graph that it is using for search from the GroumIndex object.  This GroumIndex object seems to initialize from the graph_index.json so it does not have the graph we just received through the API.

https://github.com/cuplv/FixrGraphPatternSearch/blob/musedev-integration/fixrsearch/process_pr.py#L45

I believe we need to refactor this method to take a groum file or deserialized groum object rather than a username, reponame, and hash.

If there is a better way to do this please let us know.

**Comment by smover** [comment]
@ftc you have to create a **new** GroumIndex object with the path to the graphs. Then the object will generate the json file for you. But you really don't care about the json file (its role was to cache the index on the filesystem) and in the end you just use the index object as your interface to get all the groums from a given user/repo/commit.

As I wrote in the code above:
```python
# Create the "groum" index
# path_to_the_groums is the path to the extracted groums on the filesystem
# The groums must be organized in the path_to_the_groums as "username/reponame/commitid/"
# See the folder FixrGraphPatternSearch/fixrsearch/test/data/graphs for an example.
#
groum_index = GroumIndex(graph_path)
```

So, there is no need to refactor the `process_graphs_from_commit`, just pass the groum index indexing the new groum files to process.

To be clear, in the code you wrote now you pass the groum index object indexing the graphs used to extract the patterns --- see https://github.com/cuplv/FixrGraphPatternSearch/blob/3bd7f40bf85abf0b99e1a67c69e318a59f30626d/fixrsearch/search_service.py#L96

```python
        # Create a pull request proessor
        pr_processor = PrProcessor(current_app.config[GROUM_INDEX],
                                   Search(current_app.config[CLUSTER_PATH],
     ...
```

The `current_app.config[GROUM_INDEX]` should be `GroumIndex(path_to_new_graphs_to_process)`

Let me know if you sill have doubts.

**Comment by ftc** [comment]
Thanks @smover this makes sense I didn't realize the groum index generation included the files we were trying to search for.  I will let you know if we have any more issues.

**Comment by smover** [comment]
Solved in https://github.com/cuplv/FixrGraphPatternSearch/pull/19
